version: '3'

services:
    gateway:
        build: .
        image: gateway_image
        container_name: gateway_container
        command: uvicorn main:app --reload --host 0.0.0.0 --port 8000 --workers 8

        ports:
            - 8000:8000

        env_file:
            - .env

        volumes:
            - ./src:/cephalopodus/gateway
